### ISSUE TITLE
The wiki just goes to the main page

### ISSUE THREAD

**Issue by jeremiahfallin** [pokeml/pokemon-battle-ai#6]
I'm wondering if that's intended and the wiki link in the README is supposed to just link back to the README or if that isn't intended.

**Comment by christopher-wolff** [comment]
Sorry about that, we got rid of the wiki and forgot to remove this. I replaced the link with a link to [pokemon-agents](https://github.com/pokeml/pokemon-agents).

**Comment by MalSatori** [comment]
No worries, just wanted to make sure there wasn't something I was missing.
Someone on reddit also told me that there is a discord server for Pokemon
battling with ML and mentioned a github repo but didn't say which one.
Would you happen to know about that?

**Comment by christopher-wolff** [comment]
There's a link to it in the README :) https://discordapp.com/invite/VYwe6hp

**Comment by MalSatori** [comment]
Thank you very much. :*)
